name: Clarive Remedyforce Plugin
description: Our Remedyforce Plugin has been designed to allow the automatic creation of Remedyforce views in Clarive and vice versa, so that you can have both services synchronized.
version: 1.0
icon: https://github.com/clarive/cla-remedyforce-plugin/public/icon/remedyforce.svg
url: https://github.com/clarive/cla-remedyforce-plugin
requires:
  - clarive_version: 6.8 <= version
dependencies:
  - cla-remedyforce-plugin
